#spring datasource 数据源
spring:
      datasource:
                url: jdbc:mysql://localhost:3306/tedu_store?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
                username: root
                password:
mybatis:
        mapper-locations: classpath:mappers/*.xml
